# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone

if settings.TESTING_MODE:
    OPERATIONS = []
else:
    OPERATIONS = [
        migrations.RunSQL(
                sql = [
                    "ALTER TABLE account_user MODIFY name varchar(150) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT ''"
                ],
            reverse_sql=["ALTER TABLE account_user MODIFY name varchar(150) DEFAULT ''"]
        )
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = OPERATIONS
