# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_utf8mb4'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthUnionID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=255)),
                ('unionid', models.CharField(db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='socialauthunionid',
            unique_together=set([('provider', 'uid', 'unionid')]),
        ),
    ]
