# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-31 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u6548'),
        ),
    ]
