# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20180731_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('validate', models.CharField(db_index=True, max_length=20)),
                ('token', models.CharField(db_index=True, default='', max_length=255)),
                ('status', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('request_date', models.DateField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSValidateCheckFailures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, unique=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('lockout_until', models.DateTimeField(null=True)),
            ],
        ),
    ]
